/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Accept: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/Accept.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    BtnOperate: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/GroupCall/BtnOperate/BtnOperate.vue')['default']
    Camera: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/Camera.vue')['default']
    FloatWindow: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/FloatWindow/FloatWindow.vue')['default']
    GroupCall: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/GroupCall/GroupCall.vue')['default']
    Hangup: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/Hangup.vue')['default']
    InviteCallee: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/GroupCall/InviteInfo/mobile/InviteCallee.vue')['default']
    InviteInfo: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/GroupCall/InviteInfo/InviteInfo.vue')['default']
    LivePlayer: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/SingleCall/PusherPlayer/wechat/live-player.vue')['default']
    LivePusher: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/SingleCall/PusherPlayer/wechat/live-pusher.vue')['default']
    Microphone: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/Microphone.vue')['default']
    MicVolume: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/MicVolume/MicVolume.vue')['default']
    MicVolumeClosed: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/MicVolume/MicVolumeClosed.vue')['default']
    PusherPlayer: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/GroupCall/PusherPlayer/PusherPlayer.vue')['default']
    Reject: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/Reject.vue')['default']
    RemoteStreamList: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/GroupCall/PusherPlayer/deskTop/RemoteStreamList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleAudio: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/SingleCall/InviteInfo/mobile/SingleAudio.vue')['default']
    SingleCall: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/SingleCall/SingleCall.vue')['default']
    SingleVideo: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/SingleCall/InviteInfo/mobile/SingleVideo.vue')['default']
    Speaker: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/Speaker.vue')['default']
    Swiper: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Swiper/Swiper.vue')['default']
    SwiperSlider: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Swiper/SwiperSlider.vue')['default']
    SwitchAudioCall: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/SwitchAudioCall.vue')['default']
    SwitchCamera: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/SwitchCamera.vue')['default']
    Timer: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/Timer.vue')['default']
    Toast: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Toast/Toast.vue')['default']
    ToggleSize: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/components/common/Button/ToggleSize.vue')['default']
    TUICallKit: typeof import('./../src/components/TUICallKit/src/Components/TUICallKit-vue3/TUICallKit.vue')['default']
  }
}
