import type { App } from 'vue'
import { TUIComponents, TUICore, genTestUserSig } from '@/TUIKit';
import { TUICallKit } from '@tencentcloud/call-uikit-vue';

const SDKAppID = 1400826110; // Your SDKAppID
const secretKey = '7db4d4fbd155c2d2714bfd9979285978201b818b0e3c859d5dbc6c2eb99373be'; //Your secretKey
const userID = 'test1'; // User ID

// init TUIKit
const TUIKit = TUICore.init({
  SDKAppID,
});
// TUIKit add TUIComponents
TUIKit.use(TUIComponents);
// TUIKit add TUICallKit
TUIKit.use(TUICallKit);

// login TUIKit
TUIKit.login({
  userID: userID,
  userSig: genTestUserSig({
    SDKAppID,
    secretKey,
    userID,
  }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
});

export const setupTUIKit = (app:App) => {
  app.use(TUIKit)
}
